dashboardcb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('rm_app/', include('rm_app.urls')),
    path('it_dept/', admin.site.urls),
    path('supply_chain/', include('supply_chain.urls')),
    path('member/', include('member.urls')),
    path('crisbarkopo/', include('investorkopo.urls')),
    path('crisbarmetro/', include('investormetro.urls')),
    path('', include('dashboard.urls')),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favicon.ico") ) ),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

layermanager/urls.py
from django.urls import path

from . import views

app_name = 'layermanager'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:layer_id>/', views.view_layer, name='detail'),
    path('add_layer/', views.add_layer, name='add_layer'),
    path('add_layer/post', views.add_layer_post, name='add_layer_post'),
    path('<int:layer_id>/update_layer', views.update_layer, name='update_layer'),
    path('<int:layer_id>/add_cabang/', views.add_cabang, name='add_cabang'),
    path('<int:layer_id>/add_cabang/post', views.add_cabang_post, name='add_cabang_post'),
    path('add_kategori', views.add_kategori, name="add_kategori"),
    path('add_kategori/post', views.add_kategori_post, name="add_kategori_post"),
    path('add_item', views.add_item, name="add_item"),
    path('add_item/post', views.add_item_post, name="add_item_post"),
    path('list_item', views.list_item, name="list_item"),
    path('add_modifier', views.add_modifier, name="add_modifier"),
    path('add_modifier/post', views.add_modifier_post, name="add_modifier_post"),
    path('add_modifier_varian', views.add_modifier_varian, name="add_modifier_varian"),
    path('add_modifier_varian/post', views.add_modifier_varian_post, name="add_modifier_varian_post"),
    path('add_modifier_item', views.add_modifier_item, name="add_modifier_item"),
    path('add_modifier_item/post', views.add_modifier_item_post, name="add_modifier_item_post"),
    path('remove_modifier_item/<int:item_id>/<int:modifier_id>', views.remove_modifier_item, name="remove_modifier_item"),
    path('edit_modifier_varian/<int:varian_id>', views.edit_modifier_varian, name="edit_modifier_varian"),
    path('edit_modifier_varian/<int:varian_id>/post', views.edit_modifier_varian_post, name="edit_modifier_varian_post"),
    path('<int:layer_id>/add_harga', views.add_harga, name="add_harga"),
    path('<int:layer_id>/add_harga/post', views.add_harga_post, name="add_harga_post"),
    path('edit_harga/<harga_id>', views.edit_harga, name="edit_harga"),
    path('edit_harga/<harga_id>/post', views.edit_harga_post, name="edit_harga_post"),
    path('uploadfile', views.uploadfile, name="uploadfile"),
]

member/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.halaman_login, name="login"), 
    path('logout/', views.logoutuser, name="logout"),
    
    # DEPARTEMEN IT
    path('index_it/', views.index_it, name="index_it"),
    path('akun_member/', views.akun_member, name='akun_member'),
    path('akun_backoffice/', views.akun_backoffice, name='akun_backoffice'),
    path('buat_akun_backoffice/', views.buat_akun_backoffice, name='buat_akun_backoffice'),
    path('buat_akun_member/', views.buat_akun_member, name='buat_akun_member'),
    path('detail_akun_member/<int:id_member>', views.detail_akun_member, name='detail_akun_member'),
    
    # MEMBER
    path('index/', views.index_member, name='index_member'),
    path('ubah_akun_member/', views.ubah_akun_member, name='ubah_akun_member'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

layermanager/models.py
from django.db import models

# Create your models here.
class Layer(models.Model):
    nama = models.CharField(max_length=50)
    def __str__(self):
        return self.nama

class Cabang(models.Model):
    layer = models.ForeignKey(Layer, on_delete=models.CASCADE)
    nama = models.CharField(max_length=50)
    def __str__(self):
        return self.nama

class Kategori(models.Model):
    nama = models.CharField(max_length=200)
    def __str__(self):
        return self.nama

class Item(models.Model):
    kategori = models.ForeignKey(Kategori, on_delete=models.CASCADE)
    nama = models.CharField(max_length=200)
    #kategori = models.ManyToManyField(Kategori, blank=True)
    def __str__(self):
        return self.nama

class Harga(models.Model):
    layer = models.ForeignKey(Layer, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    nama = models.CharField(max_length=200, default="Harga")
    harga_dinein = models.IntegerField(default=0)
    harga_takeaway = models.IntegerField(default=0)
    harga_gofood = models.IntegerField(default=0)
    harga_grabfood = models.IntegerField(default=0)
    harga_shopeefood = models.IntegerField(default=0)
    def __str__(self):
        return self.nama

class Modifier(models.Model):
    item = models.ManyToManyField(Item, blank=True)
    nama = models.CharField(max_length=200)
    def __str__(self):
        return self.nama

class Varian(models.Model):
    kategori = models.ForeignKey(Modifier, on_delete=models.CASCADE)
    nama = models.CharField(max_length=200)
    harga = models.IntegerField(default=0)
    def __str__(self):
        return self.nama

class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

layermanager/forms.py
from django import forms
from layermanager.models import Document

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('description', 'document', )

layermanager/views.py
#from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .decorators import unauthenticated_user

from .models import *
from .forms import DocumentForm

def logoutuser(request):
    # ini halaman logout
    logout(request)
    return redirect('loginpage')

@unauthenticated_user
def loginpage(request):

    context = {}
 
    # jika metode request adalah post
    if request.method == 'POST':
        # ambil username dan passwordnya
        username = request.POST.get('username')
        password = request.POST.get('password')

        # autentifikasi usernya
        user = authenticate(request, username=username, password=password)

        # kalau user berhasil diautentifikasi, login
        if user is not None:
            login(request, user)
            return redirect('layermanager:index')
        else:
            messages.info(request, 'username atau password salah')
            return render(request, 'login.html', context)

    return render(request, 'login.html', context)

@login_required(login_url='loginpage')
def index(request):
    layer_list = Layer.objects.order_by('-nama')
    item_count = Item.objects.count()
    modifier_count = Modifier.objects.count()
    context = {'layer_list' : layer_list, 'item_count' : item_count, 'modifier_count' : modifier_count }
    return render(request, 'layermanager/index.html', context)

@login_required(login_url='loginpage')
def view_layer(request, layer_id):
    layer = get_object_or_404(Layer, pk=layer_id)
    context = {
        'layer':layer,
    }
    return render(request, 'layermanager/view_layer.html', context)

@login_required(login_url='loginpage')
def add_layer(request):
    return render(request, 'layermanager/add_layer.html')

@login_required(login_url='loginpage')
def add_layer_post(request):
    layer = Layer(nama=request.POST.get("nama"))
    layer.save()
    return redirect('layermanager:index')

@login_required(login_url='loginpage')
def update_layer(request, layer_id):
    layer = get_object_or_404(Layer, pk=layer_id)
    layer.nama = request.POST.get("nama")
    layer.save()
    return redirect('layermanager:index')

@login_required(login_url='loginpage')
def add_cabang(request, layer_id):
    layer = get_object_or_404(Layer, pk=layer_id)
    return render(request, 'layermanager/add_cabang.html', {'layer':layer})

@login_required(login_url='loginpage')
def add_cabang_post(request, layer_id):
    layer = get_object_or_404(Layer, pk=layer_id)
    layer.cabang_set.create(nama=request.POST.get("nama"))
    layer.save()
    return redirect('layermanager:index')

@login_required(login_url='loginpage')
def add_kategori(request):
    return render(request, 'layermanager/add_kategori.html')

@login_required(login_url='loginpage')
def add_kategori_post(request):
    kategori = Kategori(nama=request.POST.get("nama"))
    kategori.save()
    return redirect('layermanager:list_item')

@login_required(login_url='loginpage')
def add_item(request):
    kategori_list = Kategori.objects.order_by('-nama')
    context = {'kategori_list': kategori_list}
    return render(request, 'layermanager/add_item.html', context)

@login_required(login_url='loginpage')
def add_item_post(request):
    kategori = get_object_or_404(Kategori, pk=request.POST.get("kategori_id"))
    kategori.item_set.create(nama=request.POST.get("nama"))
    kategori.save()
    messages.add_message(request, messages.SUCCESS, 'Successfully inserted')
    return redirect('layermanager:list_item')

@login_required(login_url='loginpage')
def list_item(request):
    messages.get_messages(request)
    kategori_list = Kategori.objects.order_by('-nama')
    modifier_list = Modifier.objects.order_by('-nama')
    context = {'kategori_list': kategori_list, 'modifier_list': modifier_list}
    return render(request, 'layermanager/list_item.html', context)

@login_required(login_url='loginpage')
def add_modifier(request):
    return render(request, 'layermanager/add_modifier.html')

@login_required(login_url='loginpage')
def add_modifier_post(request):
    modifier = Modifier(nama=request.POST.get("nama"))
    modifier.save()
    return redirect('layermanager:list_item')

@login_required(login_url='loginpage')
def add_modifier_varian(request):
    modifier_list = Modifier.objects.order_by('-nama')
    context = {'modifier_list':modifier_list}
    return render(request, 'layermanager/add_modifier_varian.html', context)

@login_required(login_url='loginpage')
def add_modifier_varian_post(request):
    modifier = get_object_or_404(Modifier, pk=request.POST.get("modifier_id"))
    modifier.varian_set.create(nama=request.POST.get("nama"), harga=request.POST.get("harga"))
    modifier.save()
    return redirect('layermanager:list_item')

@login_required(login_url='loginpage')
def edit_modifier_varian(request, varian_id):
    varian = get_object_or_404(Varian, pk=varian_id)
    context = {'varian': varian}
    return render(request, 'layermanager/edit_modifier_varian.html', context)

@login_required(login_url='loginpage')
def edit_modifier_varian_post(request, varian_id):
    varian = get_object_or_404(Varian, pk=varian_id)
    varian.nama = request.POST.get("nama")
    varian.harga = int(request.POST.get("harga").replace('.',''))
    varian.save()
    return redirect('layermanager:list_item')

@login_required(login_url='loginpage')
def add_modifier_item(request):
    modifier_list = Modifier.objects.order_by('-nama')
    item_list = Item.objects.order_by('-nama')
    context = {
        'modifier_list': modifier_list,
        'item_list': item_list,
    }
    return render(request, 'layermanager/add_modifier_item.html', context)

@login_required(login_url='loginpage')
def add_modifier_item_post(request):
    item = get_object_or_404(Item, pk=request.POST.get("item_id"))
    modifier = get_object_or_404(Modifier, pk=request.POST.get("modifier_id"))
    modifier.item.add(item)
    return redirect('layermanager:list_item')

@login_required(login_url='loginpage')
def remove_modifier_item(request, item_id, modifier_id):
    item = get_object_or_404(Item, pk=item_id)
    modifier = get_object_or_404(Modifier, pk=modifier_id)
    item.modifier_set.remove(modifier)
    return redirect('layermanager:list_item')

@login_required(login_url='loginpage')
def add_harga(request, layer_id):
    layer = get_object_or_404(Layer, pk=layer_id)
    harga_list = Harga.objects.all()
    item_id = []
    for harga in harga_list:
        item_id.append(harga.item.id)
    #kategori_list = Kategori.objects.order_by('-nama')
    item_list = Item.objects.order_by('-nama').exclude(id__in=item_id)
    context = {
        'layer': layer,
        'item_list': item_list,
        #'kategori_list': kategori_list,
    }
    return render(request, 'layermanager/add_harga.html', context)

@login_required(login_url='loginpage')
def add_harga_post(request, layer_id):
    layer = get_object_or_404(Layer, pk=layer_id)
    item = get_object_or_404(Item, pk=request.POST.get("item_id"))
    harga_dinein = int(request.POST.get("harga_dinein").replace('.',''))
    harga_takeaway = int(request.POST.get("harga_takeaway").replace('.',''))
    harga_gofood = int(request.POST.get("harga_gofood").replace('.',''))
    harga_grabfood = int(request.POST.get("harga_grabfood").replace('.',''))
    harga_shopeefood = int(request.POST.get("harga_shopeefood").replace('.',''))
    try:
        harga = get_object_or_404(Harga, layer=layer, item=item)
        if (harga_dinein > 0): harga.harga_dinein = harga_dinein
        if (harga_takeaway > 0): harga.harga_takeaway = harga_takeaway
        if (harga_gofood > 0): harga.harga_gofood = harga_gofood
        if (harga_grabfood > 0): harga.harga_grabfood = harga_grabfood
        if (harga_shopeefood > 0): harga.harga_shopeefood = harga_shopeefood
        harga.save()
        #return HttpResponse("Price edited because entry already exist")
    except:
        harga = layer.harga_set.create(nama="{}-{}".format(layer.nama, item.nama),harga_dinein=harga_dinein, harga_takeaway=harga_takeaway, harga_gofood=harga_gofood, harga_grabfood=harga_grabfood, harga_shopeefood=harga_shopeefood, item=item)
        layer.save()
        item.harga_set.add(harga)
        item.save()
    return redirect('layermanager:index')

@login_required(login_url='loginpage')
def edit_harga(request, harga_id):
    harga = get_object_or_404(Harga, pk=harga_id)
    context = {
        'harga': harga,
    }
    return render(request, 'layermanager/edit_harga.html', context)
    
@login_required(login_url='loginpage')
def edit_harga_post(request, harga_id):
    harga = get_object_or_404(Harga, pk=harga_id)
    harga.harga_dinein = int(request.POST.get("harga_dinein").replace('.',''))
    harga.harga_takeaway = int(request.POST.get("harga_takeaway").replace('.',''))
    harga.harga_gofood = int(request.POST.get("harga_gofood").replace('.',''))
    harga.harga_grabfood = int(request.POST.get("harga_grabfood").replace('.',''))
    harga.harga_shopeefood = int(request.POST.get("harga_shopeefood").replace('.',''))
    harga.save()
    return redirect('layermanager:index')

@login_required(login_url='loginpage')
def uploadfile(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return render(request, 'layermanager/uploadfile.html', {'form':form})
    else:
        form = DocumentForm()
    return render(request, 'layermanager/uploadfile.html', {'form':form})

layermanager/templates/layermanager/add_cabang.html
{% extends 'layermanager\base.html' %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="content">
            <h1>New Cabang: {{ layer.nama }}</h1>
            <form action="{% url 'layermanager:add_cabang_post' layer.id %}" method="post">
                {% csrf_token %}
                <label for="nama">Nama Cabang: </label><br>
                <input class="form-control" type="text" id="nama" name="nama"><br>
                <input class="btn btn-primary" type="submit" value="Submit">
            </form>
        </div>
    </div>
</div>
{% endblock %}

layermanager/templates/layermanager/add_harga.html
{% extends 'layermanager\base.html' %}

{% block content %}
<div class="container">
    <div class="card" style="width:25vw;">
        <div class="content">
            <h1>New Harga</h1><br>

            <form action="{% url 'layermanager:add_harga_post' layer.id %}" method="post">
                {% csrf_token %}
                <div class="form-control-group">
                    <label for="item_id">Choose Item:</label><br>
                    <select class="btn btn-default dropdown-toggle" id="item_id" name="item_id">
                        {% for item in item_list %}
                        <option value="{{ item.id }}">{{ item.nama }}</option>
                        {% endfor %}
                    </select><br><br>
                    
                    <label for="harga_dinein">Harga DineIn: </label>
                    <div class="row">
                        <div class="col col-sm-2"><h4>Rp</h4></div>
                        <div class="col col-lg"><input type="number" class="form-control" id="harga_dinein" name="harga_dinein" value=0><br></div>
                    </div>

                    <label for="harga_takeaway">Harga Takeaway: </label><br>
                    <div class="row">
                        <div class="col col-sm-2"><h4>Rp</h4></div>
                        <div class="col col-lg"><input type="number" class="form-control" id="harga_takeaway" name="harga_takeaway" value=0><br></div>
                    </div>

                    <label for="harga_gofood">Harga GoFood: </label><br>
                    <div class="row">
                        <div class="col col-sm-2"><h4>Rp</h4></div>
                        <div class="col col-lg"><input type="number" class="form-control" id="harga_gofood" name="harga_gofood" value=0><br></div>
                    </div>

                    <label for="harga_grabfood">Harga GrabFood: </label><br>
                    <div class="row">
                        <div class="col col-sm-2"><h4>Rp</h4></div>
                        <div class="col col-lg"><input type="number" class="form-control" id="harga_grabfood" name="harga_grabfood" value=0><br></div>
                    </div>

                    <label for="harga_shopeefood">Harga ShopeeFood: </label><br>
                    <div class="row">
                        <div class="col col-sm-2"><h4>Rp</h4></div>
                        <div class="col col-lg"><input type="number" class="form-control"id="harga_shopeefood" name="harga_shopeefood" value=0><br></div>
                    </div>

                    <input type="submit" class="btn btn-primary" value="Submit">
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

layermanager/templates/layermanager/add_item.html
{% extends 'layermanager\base.html' %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="content">
            <h1>New Item</h1>

            <form action="{% url 'layermanager:add_item_post' %}" method="post">
                {% csrf_token %}
                <label for="kategori_id">Choose Kategori:</label><br>
                <select class="btn btn-dropdown" id="kategori_id" name="kategori_id">
                    {% for kategori in kategori_list %}
                        <option value="{{ kategori.id }}">{{ kategori.nama }}</option>
                    {% endfor %}
                </select><br><br>
                <label for="nama">Nama Item: </label><br>
                <input type="text" class="form-control" id="nama" name="nama"><br>
                <input type="submit" class="btn btn-primary" value="Submit">
            </form>
        </div>
    </div>
</div>
{% endblock %}

layermanager/templates/layermanager/add_kategori.html
{% extends 'layermanager\base.html' %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="content">
            <h1>New Kategori</h1>

            <form action="{% url 'layermanager:add_kategori_post' %}" method="post">
                {% csrf_token %}
                <label for="nama">Nama Kategori: </label><br>
                <input type="text" class="form-control" id="nama" name="nama"><br>
                <input type="submit" class="btn btn-primary" value="Submit">
            </form>
        </div>
    </div>
</div>
{% endblock %}

layermanager/templates/layermanager/add_layer.html
{% extends 'layermanager\base.html' %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="content">
            <h1>New Layer</h1>

            <form action="{% url 'layermanager:add_layer_post' %}" method="post">
                {% csrf_token %}
                <label for="nama">Nama Layer: </label><br>
                <input class="form-control" type="text" id="nama" name="nama"><br>
                <input class="btn btn-primary" type="submit" value="Submit">
            </form>
        </div>
    </div>
</div>
{% endblock %}

layermanager/templates/layermanager/add_modifier.html
{% extends 'layermanager\base.html' %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="content">
            <h1>New Modifier</h1>

            <form action="{% url 'layermanager:add_modifier_post' %}" method="post">
                {% csrf_token %}
                <label for="nama">Nama Modifier: </label><br>
                <input type="text" class="form-control" id="nama" name="nama"><br>
                <input type="submit" class="btn btn-primary" value="Submit">
            </form>
        </div>
    </div>
</div>
{% endblock %}

layermanager/templates/layermanager/index.html
{% extends 'layermanager\base.html' %}

{% block content %}
<div class="container-fluid">

    <div class="row">
        <div class="col">
            <div class="card" style="width:40vw;">
                <div class="content">
                    <h1>Layer</h1>
                    <p>Pilih salah satu <b>Layer</b> di bawah ini</p>
                    {% if layer_list %}
                    {% for layer in layer_list %}
                    <a href="{% url 'layermanager:detail' layer.id %}" class="btn btn-outline-warning" style="font-size:125%; border-radius: 60px 60px 60px 60px; width:50%; margin-top:1%; text-align:left;">{{ layer.nama }}</a><br>
                    {% endfor %}
                    {% else %}
                        <p>No Layer is available</p>
                    {% endif %}
                    <a class="btn btn-primary" href="{% url 'layermanager:add_layer' %}" role="button" style="margin-top:3%; margin-bottom:1%;">Add new Layer</a>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card" style="width:40vw;">
                <div class="content">
                    <h1>Items</h1>
                    <p>Jumlah Item yang tersedia : {{ item_count }}</p>
                    <p>Jumlah Modifier yang tersedia : {{ modifier_count }}</p>
                    <a class="btn btn-primary" href="{% url 'layermanager:list_item' %}" role="button">Item & Modifier List</a>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

layermanager/templates/layermanager/list_item.html
{% extends 'layermanager\base.html' %}

{% block content %}
<div class="container-fluid" style="width:90vw">
    {% if messages %}
        {% for messages in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}
    <div class="row">
        <div class="col">


            <div class="card">
                <div class="content">
                    <h1>Item</h1>
                    <a href="{% url 'layermanager:add_kategori' %}" class="button">Add new Kategori</a><br>
                    <a href="{% url 'layermanager:add_item' %}" class="button">Add new Item</a><br>
                    <a href="{% url 'layermanager:add_modifier_item' %}" class="button">Add Modifier to Item</a><br>
                </div>
            </div>


            {% if kategori_list %}
                    {% for kategori in kategori_list %}
                    <div class="card">
                        <div class="content">
                            <h3> {{ kategori.nama }} </h3>
                            <table class="table" style="width:100%; text-align:left; color:white;">
                                <tr>
                                    <th>Item</th>
                                    <th>Modifiers</th>
                                </tr>
                                {% for item in kategori.item_set.all %}
                                <tr>
                                    <th>{{ item.nama }}</th>
                                    <th>
                                        {% for modifier in item.modifier_set.all %} 
                                        <a href="{% url 'layermanager:remove_modifier_item' item.id modifier.id %}" class="btn btn-danger" style="border-radius:60px 60px 60px 60px; margin-top:1%">X</a> {{ modifier }}<br>
                                        {% endfor %}
                                        <br><br>
                                    </th>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                    {% endfor %}
                {% else %}
				<div class="card">
					<div class="content">
						<p>No Item is available</p>
					</div>
				</div>
                {% endif %}


        </div>

        
        <div class="col-sm">
                

            <div class="card">
                <div class="content">
                    <h1>Modifier</h1>
                    <a href="{% url 'layermanager:add_modifier' %}" class="button">Add new Modifier Kategori</a><br>
                    <a href="{% url 'layermanager:add_modifier_varian' %}" class="button">Add new Modifier Varian</a><br>
                </div>
            </div>


            {% if modifier_list %}
                    {% for modifier in modifier_list %}
                    <div class="card"">
                        <div class="content">
                            <h3> {{ modifier.nama }} </h3>
                            <table class="table" style="text-align:left; color:white;">
                            <tr>
                                <th>Nama Varian</th>
                                <th>Harga</th>
                            </tr>
                            {% for varian in modifier.varian_set.all %}
                            <tr>
                                <th>{{ varian.nama }}</th>
                                <th>Rp{{ varian.harga }}</th>
                                <th><form action="{% url 'layermanager:edit_modifier_varian' varian.id %}"><input type="submit" class="btn btn-primary" value="Edit"></form></th>
                            </tr>
                            {% endfor %}
                            </table>
                        </div>
                    </div>
                    {% endfor %}
                    
                {% else %}
                <div class="card">
					<div class="content">
						<p>No Modifier is available</p>
					</div>
                </div>
                {% endif %}


        </div>
    </div>
</div>
{% endblock %}

layermanager/templates/layermanager/view_layer.html
{% extends 'layermanager\base.html' %}

{% block content %}
<div class="container-fluid" style="width:60vw">
    <div class="row">

        
        <div class="col">
            <div class="card">
                <form action="{% url 'layermanager:update_layer' layer.id %}" method="post">
                    <div class="content" style="margin:2%;">
                        {% csrf_token %}
                        <label for="nama"><h2>Nama Layer: </h2></label><br>
                        <div class="input-group">
                            <input class="form-control" type="text" id="nama" name="nama" value="{{ layer.nama }}">
                            <span class="input-group-btn">
                                <input type="submit" class="btn btn-primary" style="border-radius:0px 5px 5px 0px;" value="Save">
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            
            <div class="card">
                <div class="content" style="margin:2%;">
                    <h2>Cabang</h2>
                    <form action="{% url 'layermanager:add_cabang' layer.id %}">
                        <input type="submit" class="btn btn-primary" value="Add new Cabang">
                    </form>
            
                    {% if layer.cabang_set %}
                    <ul>
                    {% for cabang in layer.cabang_set.all %}
                        <li>{{ cabang.nama }}</li>
                    {% endfor %}
                    </ul>
                    {% else %}
                    This layer does not have any Cabang
                    {% endif %}
                </div>
            </div>        
        </div>


        <div class="col">
            <div class="card" style="position:absolute; width:60vw;">
                <div class="content" style="margin:2%;">
                    <h2>Harga</h2>
                    <form action="{% url 'layermanager:add_harga' layer.id %}"><input type="submit" class="btn btn-primary" value="Add new harga"></form>
                    {% if layer.harga_set %}
                    <table class="table" style="width:100%; color:white;">
                        <tr>
                            <th>Item</th>
                            <th>Kategori</th>
                            <th>Harga DineIn</th>
                            <th>Harga Takeaway</th>
                            <th>Harga GoFood</th>
                            <th>Harga GrabFood</th>
                            <th>Harga ShopeeFood</th>
                        </tr>
                        {% for harga in layer.harga_set.all %}
                            <tr>
                                <th>{{ harga.item.nama }}</th>
                                <th>{{ harga.item.kategori }}</th>
                                <th>Rp{{ harga.harga_dinein }}</th>
                                <th>Rp{{ harga.harga_takeaway }}</th>
                                <th>Rp{{ harga.harga_gofood }}</th>
                                <th>Rp{{ harga.harga_grabfood }}</th>
                                <th>Rp{{ harga.harga_shopeefood }}</th>
                                <th><form action="{% url 'layermanager:edit_harga' harga.id %}"><input type="submit" class="btn btn-primary" value="Edit"></form></th>
                            </tr>    
                        {% endfor %}
                    </table>
                    {% else %}
                    Tidak ada data harga
                    {% endif %}
                </div>
            </div>
        </div>


    </div>
</div>

{% endblock %}